
Students Placement Prediction using Logistics Regression


#Get understanding about Data set

The variables in dataset

1.student_ID

2.CGPA

3.IQ

4.Placememt

#Import library

In [1]:
import pandas as pd

In [8]:
import numpy as np

#Import CSV as data frame

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/refs/heads/main/Placement.csv')

#Get first five rows of the dataframe

In [7]:
df.head()

Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

#get information of dataframe

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.2 KB


#get the summary statistics

In [11]:
df.describe()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

#Get the coloumn name

In [12]:
df.columns

Index(['Student_ID', 'CGPA', 'IQ', 'Placement'], dtype='object')

#Get shape of data frame

In [13]:
df.shape

(100, 4)

#Get unique values in y variable

In [16]:
df['Placement'].value_counts()

Placement
1    50
0    50
Name: count, dtype: int64

In [17]:
df.groupby('Placement').mean()

Student_ID   CGPA      IQ
Placement                           
0               46.32  5.056  126.88
1               54.68  6.926  120.28

#Define X and y

In [18]:
y=df['Placement']

In [19]:
y.shape

(100,)

In [20]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

In [21]:
X=df[['CGPA','IQ']]

In [22]:
X=df.drop(['Student_ID','Placement'],axis=1)

In [23]:
X.shape

(100, 2)

In [24]:
X

CGPA   IQ
0    6.8  123
1    5.9  106
2    5.3  121
3    7.4  132
4    5.8  142
..   ...  ...
95   4.3  200
96   4.4   42
97   6.7  182
98   6.3  103
99   6.2  113

[100 rows x 2 columns]

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
ss=StandardScaler()

In [27]:
ss.fit_transform(X)


array([[ 0.71095807, -0.01459341],
       [-0.0799718 , -0.44233119],
       [-0.60725838, -0.0649155 ],
       [ 1.23824465,  0.21185601],
       [-0.16785289,  0.46346647],
       [ 0.97460136, -1.90167186],
       [-0.25573399,  0.48862751],
       [-0.87090167, -1.52425617],
       [ 0.0957904 ,  0.81572111],
       [-0.78302057, -1.44877303],
       [ 0.0079093 , -1.977155  ],
       [ 0.79883917,  0.36282228],
       [-0.51937728,  0.38798333],
       [ 0.35943369, -0.19072073],
       [ 0.0957904 , -0.51781433],
       [-0.78302057,  1.31894203],
       [-0.69513948,  2.52667224],
       [-2.36488031,  1.49506935],
       [-1.74971264, -0.59329747],
       [-0.69513948,  0.21185601],
       [ 0.53519588, -0.09007654],
       [ 0.97460136,  0.68991588],
       [-0.95878277, -0.09007654],
       [-1.13454496, -0.92039106],
       [-1.13454496, -0.0649155 ],
       [-0.87090167, -0.81974688],
       [ 0.88672027,  1.89764609],
       [ 0.0079093 ,  0.01056764],
       [-0.69513948,

In [28]:
X.shape

(100, 2)

#Train Test Model

In [29]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y,random_state=2529)


In [34]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape


((70, 2), (30, 2), (70,), (30,))

#Get model train

In [35]:
from sklearn.linear_model import LogisticRegression

In [41]:
lr=LogisticRegression ()

In [42]:
lr.fit(X_train,y_train)

LogisticRegression()

#Get model prediction

In [43]:
y_pred=lr.predict(X_test)

In [44]:
y_pred.shape

(30,)

In [45]:
y_pred

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1])

In [46]:
lr.predict_proba(X_test)

array([[7.06655606e-02, 9.29334439e-01],
       [9.58627888e-01, 4.13721125e-02],
       [8.42243847e-01, 1.57756153e-01],
       [9.62609884e-02, 9.03739012e-01],
       [4.46846223e-01, 5.53153777e-01],
       [9.71553371e-01, 2.84466287e-02],
       [1.05792783e-01, 8.94207217e-01],
       [7.70877471e-02, 9.22912253e-01],
       [9.08743146e-01, 9.12568539e-02],
       [1.85143489e-01, 8.14856511e-01],
       [9.71446529e-01, 2.85534707e-02],
       [9.65852225e-01, 3.41477746e-02],
       [4.21055058e-01, 5.78944942e-01],
       [2.93878092e-01, 7.06121908e-01],
       [1.97932310e-03, 9.98020677e-01],
       [9.66670869e-01, 3.33291306e-02],
       [9.52918218e-04, 9.99047082e-01],
       [5.04258684e-02, 9.49574132e-01],
       [9.67832909e-01, 3.21670907e-02],
       [8.95493737e-02, 9.10450626e-01],
       [3.22482144e-03, 9.96775179e-01],
       [8.53904082e-01, 1.46095918e-01],
       [9.85301028e-01, 1.46989724e-02],
       [9.28441236e-01, 7.15587640e-02],
       [9.720431

In [47]:
from sklearn.metrics import confusion_matrix, classification_report

In [48]:
print(confusion_matrix,(y_test,y_pred))

<function confusion_matrix at 0x7c8497e530a0> (66    1
40    0
41    0
93    1
71    1
23    0
43    1
26    1
19    0
79    1
34    0
59    0
14    0
98    1
53    1
80    0
69    1
21    1
94    0
35    1
37    1
12    0
96    0
86    0
75    0
63    1
30    1
39    0
73    0
97    1
Name: Placement, dtype: int64, array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1]))


In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



#Get future predictions

In [50]:
X_new=df.sample(1)

In [51]:
X_new

Student_ID  CGPA   IQ  Placement
1           2   5.9  106          0

In [52]:
X_new.shape

(1, 4)

In [54]:
X_new=X_new.drop(['Student_ID','Placement'],axis=1)

In [55]:
X_new

CGPA   IQ
1   5.9  106

In [56]:
X_new.shape

(1, 2)

In [57]:
X_new=ss.fit_transform(X_new)

In [58]:
y_pred_new=lr.predict(X_new)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [59]:
y_pred_new

array([0])

In [61]:
lr.predict_proba(X_new)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[9.99999919e-01, 8.06611723e-08]])